#!/bin/bash

. /etc/rc.conf
. /etc/rc.d/functions

name=dunstd
PID=$(pidof -o %PPID /usr/bin/dunst)

start__daemon() {
	{ /usr/bin/dunst | logger --priority user.notice -t "$name" & } 2>&1 \
		| logger --priority user.error -t "$name"&
}

case "$1" in
	start)
		stat_busy "Starting $name daemon"
		[ -z "$PID" ] &&start__daemon \
			&& stat_done \
			|| { stat_fail; exit 1; }
		;;
	stop)
		stat_busy "Stopping $name daemon"
		[ -n "$PID" ] && kill $PID >/dev/null \
			&& stat_done \
			|| { stat_fail; exit 1; }
		;;
#reload)
#	stat_busy "Reloading $name daemon"
#	[[ -n "$PID" ]] && kill -HUP $PID &>/dev/null \
#		&& { stat_done; } \
#		|| { stat_fail; exit 1; }
#		;;
restart)
	$0 stop
	sleep 1
	$0 start
	;;
*)
	echo "usage: $0 {start|stop|restart|reload}"
	;;
esac
exit 0
