#!/bin/sh

if [ "$1" = "home" ]; then
	xrandr --output eDP1 --primary --mode 1366x768 --pos 1680x0 --rotate normal --output DP1 --off --output DP2 --off --output DP3 --mode 1680x1050 --pos 0x0 --rotate normal --output HDMI1 --off --output HDMI2 --off --output VIRTUAL1 --off --output DP1-2 --off --output DP1-3 --off --output DP1-1 --off
elif [ "$1" = "dp" ]; then
	xrandr --output eDP1 --primary --mode 1366x768 --pos 0x0 --rotate normal --output DP1 --off --output DP2 --off --output DP3 --off --output HDMI1 --off --output HDMI2 --off --output VIRTUAL1 --off --output DP1-2 --off --output DP1-3 --off --output DP1-1 --off
elif [ "$1" = "kronos" ]; then
	xrandr --output eDP1 --primary --mode 1366x768 --pos 1187x1080 --rotate normal --output DP1 --off --output DP1-1 --crtc 2 --mode 1920x1080 --pos 0x0 --rotate normal --output DP1-2 --off --output DP1-3 --crtc 1 --mode 1920x1080 --pos 1920x0 --rotate normal --output DP2 --off --output DP3 --off --output HDMI1 --off --output HDMI2 --off --output VIRTUAL1 --off
else
	arandr
fi

"$HOME"/.fehbg
