#!/bin/sh

if [ "$1" = "home" ]; then
	xrandr --output eDP1 --mode 1920x1080 --pos 1680x0 --rotate normal --output HDMI1 --off --output DP1 --primary --mode 1680x1050 --pos 0x0 --rotate normal --output VIRTUAL1 --off
elif [ "$1" = "dp" ]; then
	xrandr --output eDP1 --primary --mode 1920x1080 --pos 0x0 --rotate normal --output DP1 --off --output HDMI1 --off --output VIRTUAL1 --off
else
	arandr
fi

"$HOME"/.fehbg
