#!/bin/sh

#while true; do
#	dbus-send --system --type=method_call \
#		--dest=org.freedesktop.UPower \
#		/org/freedesktop/UPower/devices/battery_BAT1 \
#		org.freedesktop.UPower.Device.Refresh
#
#	sleep 30
#done

{ inotifywait -me access /sys/class/power_supply/BAT1/uevent 2>/dev/null; } | while read line; do
	#echo $line
	pkill -SIGRTMIN+5 i3blocks
done
